### ISSUE TITLE
Can't seem to replicate sentiment embedding

### ISSUE THREAD

**Issue by hnstr** [peace195/aspect-based-sentiment-analysis#3]
How did you obtain the sentiment embedding (sswe-u.txt)? I can't seem to find anything about it in the README, and the file isn't explained in the drive either. I am trying to replicate the results on a different language, so evidently I need to retrain the sentiment embeddings. 

Also, how did you acquire the incremental/decremental/negative/positive/reverse/stop words?

**Comment by peace195** [comment]
@hnstr If you want to replicate the results on a different language, you have to build your own incremental/decremental/negative/positive/reverse/stop words set in that language.

- Sentiment embeddings: [See Tang et al. 2014. Learning Sentiment-SpecificWord Embedding for Twitter Sentiment Classification for more details.](http://aclweb.org/anthology/P14-1146)
- incremental/decremental/negative/positive/reverse/stop words: [Opinion Lexicon (6800 words).](https://www.cs.uic.edu/~liub/FBS/sentiment-analysis.html#lexicon)
