### ISSUE TITLE
Is this correct?

### ISSUE THREAD

**Issue by hnstr** [peace195/aspect-based-sentiment-analysis#4]
Hi, why do you use

`sentiment = tf.multiply(sentiment, tf.expand_dims(self.tf_X_binary_mask, 2))` on line 178 in `sa_aspect_oop.py`? It seems highly influential on the results, and I wonder if it is right, since it seems to use the ground truth in the prediction?

**Comment by peace195** [comment]
@hnstr Yes, it is. This operation increases the classification accuracy.

**Comment by hnstr** [comment]
I understand that it increases the classification accuracy, but if I want to classify without the ground truth (so real-world examples), the model will not work. Or otherwise I might have missed something, would you happen to know what could be the problem?

**Comment by peace195** [comment]
@hnstr If you want to classify the real-world examples, you have to generate the bit-mask vectors of these examples. It is easy to generate the bit-mask vectors because you know the position of aspects expressed in the review/comment.

**Comment by hnstr** [comment]
But if I would know the position of those aspects, I wouldn't need a model for it, would I?

**Comment by peace195** [comment]
Yes, exactly!

**Comment by arundprabhu** [comment]
@hnstr  Were you successful in using this for the real world examples?
